name: mobial
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter:
  flutter_advanced_drawer: ^1.3.0
  image_picker:
  settings_ui:
  file_picker:
  flutter_chat_types:
  flutter_chat_ui:
  mime:
  intl:
  open_file:
  uuid:
  google_maps_flutter: ^2.1.1
  carousel_slider: ^4.0.0
  qrscan: ^0.3.2
  flutter_barcode_scanner: ^2.0.0
  flutter_map: any
  latlong2: ^0.8.0
  google_fonts: ^2.1.1
  date_field: ^2.1.3
  http: ^0.13.4

flutter:
  uses-material-design: true

  assets:
    - assets/img/

 