name: mobial
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter:
  flutter_advanced_drawer: ^1.3.0
  image_picker:
  settings_ui:
  file_picker:
  flutter_chat_types:
  flutter_chat_ui:
  mime:
  intl:
  open_file:
  uuid:
  google_maps_flutter:
  carousel_slider:
  qrscan:
  flutter_barcode_scanner:
  flutter_map:
  flutter_map_marker_cluster: any
  latlong2:
  google_fonts:
  date_field:
  http:
  syncfusion_flutter_maps:
  animated_theme_switcher:
  cloud_firestore: ^3.1.5
  firebase_core: ^1.10.6
  localstorage: ^4.0.0+1
  geocoding: ^2.0.1
  azblob: ^2.0.0
  path: ^1.8.0
  flutter_markdown:
  dropdown_search: ^0.6.3
  curved_navigation_bar: ^1.0.1
  flutter_spinkit: ^5.1.0
  pull_to_refresh: ^2.0.0
  firebase_messaging: ^11.2.5
  flutter_local_notifications: ^9.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/bial_location.json

 